// import modules for testing
const mail = require('../handlers/MailHandler');
const assert = require('assert');

// tesing MailHandler
describe("MailHandler", async function() {
    const mailHandler = new mail();
    this.timeout(5000);
    it(`Escenario: Cuando se desee enviar un correo electronico`, async function () {
        const mailOptions = {
            from: '"Just Talk." <just.talk.team.2021@gmail.com>',
            to: "U201711778@upc.edu.pe",
            subject: 'Successful test',
            text: 'This is an autogenerated message'
        };
        const functionResult = await mailHandler.sendMail(mailOptions);
        assert.strictEqual(functionResult, 1, `No se envio el correo correctamente`);
    });
});