name: automatization

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  Continuos-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup nodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install Dependencies
        run: npm ci
        working-directory: ./functions
      - name: Test
        run: npm run test
        working-directory: ./functions

  Continuos-Delivery:
    name: Continuos-Delivery
    needs: Continuos-Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node JS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install Dependencies
        run: npm ci
        working-directory: ./functions
      - name: Deploy to Firebase Development Project
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project=${{ secrets.FIREBASE_ALIAS_DEVELOPMENT }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_DEVELOPMENT }}
    if: ${{ github.event_name == 'pull_request' }}

  Continuos-Deployment:
    name: Continuos-Deployment
    needs: Continuos-Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node JS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install Dependencies
        run: npm ci
        working-directory: ./functions
      - name: Deploy to Firebase Production Project
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project=${{ secrets.FIREBASE_ALIAS_PRODUCTION }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_PRODUCTION }}
    if: ${{ github.event_name == 'push' }}