name: continuous_delivery

on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node JS
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Dependencies
        run: npm ci
        working-directory: ./functions
  deploy:
    name: Delivery
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project=${{ secrets.FIREBASE_ALIAS_DEVELOPMENT }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_DEVELOPMENT }}